SEASON_DROPDOWN = "season-dropdown"
SELECT_ALL_SEASON_BUTTON = "select-all-season-button"
TAKER_DROPDOWN = "taker-dropdown"
SELECT_ALL_TAKER_BUTTON = "select-all-taker-button"
CONTRACT_DROPDOWN = "contract-dropdown"
SELECT_ALL_CONTRACT_BUTTON = "select-all-contract-button"

BARCHART_TAKER = "barchart-taker"
TABLE_TAKER = "table_taker"
LINES_RANKING = "lines-ranking"
RANKING_CARDS = "ranking-cards"